#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Signoff.Resource", IsApplication=true)]

namespace Signoff
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cellback = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CustomSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo_galaxy_black_64 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int DateSigned = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int Image = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int List = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int NameSigned = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Text = 2131230720;
			
			// aapt resource value: 0x7f08000e
			public const int btnClear = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int btnHistory = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int btnSave = 2131230733;
			
			// aapt resource value: 0x7f080005
			public const int btnSearch = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int btnSort = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int label = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int label_signature = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int nameText = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int rootView = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int searchName = 2131230724;
			
			// aapt resource value: 0x7f08000c
			public const int signatureView = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int HistoryDisplay = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int HomeScreen = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
